apiVersion: v1
data:
  CASSANDRA_SEEDS: cassandra-cassandra-svc
  EUREKA_URI: http://servicediscovery-internal-service:8761/eureka
  MONGO_URI: mongodb://mongo-internal-service:27017/ses?replicaSet=rs0
  RABBITMQ_SEED: rabbitmq-rabbitmq-discovery
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CASSANDRA_SEEDS":"cassandra-cassandra-svc","EUREKA_URI":"http://servicediscovery-internal-service:8761/eureka","MONGO_URI":"mongodb://mongo-internal-service:27017/ses?replicaSet=rs0"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"powerinfrastructureservice"},"name":"powerinfrastructureservice-config","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/powerinfrastructureservice-config"}}
  creationTimestamp: null
  labels:
    app: powerinfrastructureservice
  name: powerinfrastructureservice-config
  selfLink: /api/v1/namespaces/default/configmaps/powerinfrastructureservice-config
