apiVersion: v1
data:
  metrics.enabled: "false"
  metrics.image: gcr.io/cloud-marketplace/google/rabbitmq/prometheus-to-sd@sha256:8e3679a6e059d1806daae335ab08b304fd1d8d35cdff457baded7306b5af9ba5
  name: rabbitmq
  namespace: default
  rabbitmq.erlangCookie: Tm11eTRDaWQyNzJRbWRRSll4WVAxbmVGRXV1UkhEaFk=
  rabbitmq.image: gcr.io/cloud-marketplace/google/rabbitmq@sha256:2f34801993bcde94aa1edd645755d01cb5af634ba53c9ea5a44202a35550ed3f
  rabbitmq.initImage: gcr.io/cloud-marketplace/google/rabbitmq/debian9@sha256:b7251aac422f8314b3a204ca13488f49673dc7764303c1c23dae332e6f46ca73
  rabbitmq.password: WnNHUkxCNVhwQTlo
  rabbitmq.replicas: "3"
  rabbitmq.serviceAccount: rabbitmq
  rabbitmq.user: guest
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: deployer.marketplace.cloud.google.com
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq-deployer-config
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: Application
    name: rabbitmq
    uid: 23a19598-f977-11e9-a465-42010a80005e
  selfLink: /api/v1/namespaces/default/configmaps/rabbitmq-deployer-config
