apiVersion: v1
data:
  EUREKA_URI: http://servicediscovery-0.servicediscovery-internal-service.default.svc.cluster.local:8761/eureka/,http://servicediscovery-1.servicediscovery-internal-service.default.svc.cluster.local:8761/eureka/
  MULTIPLE_EUREKA_INSTANCES: "true"
  POD_SERVICE: .servicediscovery-internal-service.default.svc.cluster.local
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"EUREKA_URI":"http://servicediscovery-0.servicediscovery-internal-service.default.svc.cluster.local:8761/eureka/,http://servicediscovery-1.servicediscovery-internal-service.default.svc.cluster.local:8761/eureka/","MULTIPLE_EUREKA_INSTANCES":"true","POD_SERVICE":".servicediscovery-internal-service.default.svc.cluster.local"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"servicediscovery"},"name":"servicediscovery-config","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/servicediscovery-config"}}
  creationTimestamp: null
  labels:
    app: servicediscovery
  name: servicediscovery-config
  selfLink: /api/v1/namespaces/default/configmaps/servicediscovery-config
