apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"cassandra-server","app.kubernetes.io/name":"cassandra"},"name":"cassandra-cassandra-svc","namespace":"default","selfLink":"/api/v1/namespaces/default/services/cassandra-cassandra-svc"},"spec":{"clusterIP":"None","ports":[{"name":"cql","port":9042,"protocol":"TCP","targetPort":9042},{"name":"thrift","port":9160,"protocol":"TCP","targetPort":9160}],"selector":{"app.kubernetes.io/component":"cassandra-server","app.kubernetes.io/name":"cassandra"},"sessionAffinity":"ClientIP","sessionAffinityConfig":{"clientIP":{"timeoutSeconds":10800}},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: cassandra-server
    app.kubernetes.io/name: cassandra
  name: cassandra-cassandra-svc
  selfLink: /api/v1/namespaces/default/services/cassandra-cassandra-svc
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: 9042
  - name: thrift
    port: 9160
    protocol: TCP
    targetPort: 9160
  selector:
    app.kubernetes.io/component: cassandra-server
    app.kubernetes.io/name: cassandra
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
