apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"cassandra-server","app.kubernetes.io/name":"cassandra"},"name":"cassandra-external-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/cassandra-external-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"port":9042,"protocol":"TCP","targetPort":9042}],"selector":{"app.kubernetes.io/component":"cassandra-server","app.kubernetes.io/name":"cassandra"},"sessionAffinity":"ClientIP","sessionAffinityConfig":{"clientIP":{"timeoutSeconds":10800}},"type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: cassandra-server
    app.kubernetes.io/name: cassandra
  name: cassandra-external-service
  selfLink: /api/v1/namespaces/default/services/cassandra-external-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31838
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app.kubernetes.io/component: cassandra-server
    app.kubernetes.io/name: cassandra
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
status:
  loadBalancer: {}
