apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"configserver"},"name":"configserver-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/configserver-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":31604,"port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"configserver"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: configserver
  name: configserver-service
  selfLink: /api/v1/namespaces/default/services/configserver-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31604
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: configserver
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
