apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"frontend"},"name":"frontend-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/frontend-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":30458,"port":8082,"protocol":"TCP","targetPort":8082}],"selector":{"app":"frontend"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend-service
  selfLink: /api/v1/namespaces/default/services/frontend-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30458
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
