apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"gateway"},"name":"gateway-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/gateway-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":31032,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"gateway"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway-service
  selfLink: /api/v1/namespaces/default/services/gateway-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31032
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
