apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"mongo-server","app.kubernetes.io/name":"mongo"},"name":"mongo-external-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/mongo-external-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":31941,"port":27017,"protocol":"TCP","targetPort":27017}],"selector":{"app.kubernetes.io/component":"mongo-server","app.kubernetes.io/name":"mongo"},"sessionAffinity":"ClientIP","sessionAffinityConfig":{"clientIP":{"timeoutSeconds":10800}},"type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: mongo-server
    app.kubernetes.io/name: mongo
  name: mongo-external-service
  selfLink: /api/v1/namespaces/default/services/mongo-external-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31941
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app.kubernetes.io/component: mongo-server
    app.kubernetes.io/name: mongo
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
status:
  loadBalancer: {}
