apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"powerinfrastructureservice"},"name":"powerinfrastructureservice-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/powerinfrastructureservice-service"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":31694,"port":8083,"protocol":"TCP","targetPort":8083}],"selector":{"app":"powerinfrastructureservice"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: powerinfrastructureservice
  name: powerinfrastructureservice-service
  selfLink: /api/v1/namespaces/default/services/powerinfrastructureservice-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31694
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: powerinfrastructureservice
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
