apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"servicediscovery-server","app.kubernetes.io/name":"servicediscovery"},"name":"servicediscovery-internal-service","namespace":"default","selfLink":"/api/v1/namespaces/default/services/servicediscovery-internal-service"},"spec":{"clusterIP":"None","ports":[{"name":"registry","port":8761,"protocol":"TCP","targetPort":8761}],"selector":{"app.kubernetes.io/component":"servicediscovery-server","app.kubernetes.io/name":"servicediscovery"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: servicediscovery-server
    app.kubernetes.io/name: servicediscovery
  name: servicediscovery-internal-service
  selfLink: /api/v1/namespaces/default/services/servicediscovery-internal-service
spec:
  clusterIP: None
  ports:
  - name: registry
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app.kubernetes.io/component: servicediscovery-server
    app.kubernetes.io/name: servicediscovery
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
