apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":null,"generation":1,"labels":{"app":"configserver"},"name":"configserver","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/configserver"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"configserver"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"configserver"}},"spec":{"containers":[{"env":[{"name":"EUREKA_URI","valueFrom":{"configMapKeyRef":{"key":"EUREKA_URI","name":"configserver-config"}}},{"name":"POD_SERVICE","value":"gateway-service"}],"image":"soelmanm/smart-energy-system:configserver","imagePullPolicy":"Always","name":"smart-energy-system","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: configserver
  name: configserver
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/configserver
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: configserver
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configserver
    spec:
      containers:
      - env:
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: configserver-config
        - name: POD_SERVICE
          value: configserver-service
        image: soelmanm/smart-energy-system:configserver
        imagePullPolicy: Always
        name: smart-energy-system
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
