apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"deviceactivity"},"name":"deviceactivity","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"deviceactivity"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"deviceactivity"}},"spec":{"containers":[{"env":[{"name":"EUREKA_URI","valueFrom":{"configMapKeyRef":{"key":"EUREKA_URI","name":"frontend-config"}}},{"name":"RABBITMQ_SEED","value":"rabbitmq-rabbitmq-discovery"}],"image":"soelmanm/smart-energy-system:deviceactivity","imagePullPolicy":"Always","name":"smart-energy-system","resources":{"requests":{"cpu":"10m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: deviceactivity
  name: deviceactivity
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/deviceactivity
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deviceactivity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deviceactivity
    spec:
      containers:
      - env:
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: frontend-config
        - name: RABBITMQ_SEED
          value: rabbitmq-rabbitmq-discovery
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: ZsGRLB5XpA9h
        - name: HOUSEHOLD_API_URL
          value: http://gateway-service/api/households
        image: soelmanm/smart-energy-system:deviceactivity
        imagePullPolicy: Always
        name: smart-energy-system
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
