apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":null,"generation":1,"labels":{"app":"gateway"},"name":"gateway","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/gateway"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"gateway"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"gateway"}},"spec":{"containers":[{"env":[{"name":"EUREKA_URI","valueFrom":{"configMapKeyRef":{"key":"EUREKA_URI","name":"gateway-config"}}},{"name":"POD_SERVICE","value":"gateway-service"}],"image":"soelmanm/smart-energy-system:gateway","imagePullPolicy":"Always","name":"smart-energy-system","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: gateway
  name: gateway
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - env:
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: gateway-config
        - name: POD_SERVICE
          value: gateway-service
        image: soelmanm/smart-energy-system:gateway
        imagePullPolicy: Always
        name: smart-energy-system
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
