apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6"},"creationTimestamp":null,"generation":1,"labels":{"app":"powerinfrastructureservice"},"name":"powerinfrastructureservice","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/powerinfrastructureservice"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"powerinfrastructureservice"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"powerinfrastructureservice"}},"spec":{"containers":[{"env":[{"name":"EUREKA_URI","valueFrom":{"configMapKeyRef":{"key":"EUREKA_URI","name":"powerinfrastructureservice-config"}}},{"name":"CASSANDRA_SEEDS","valueFrom":{"configMapKeyRef":{"key":"CASSANDRA_SEEDS","name":"powerinfrastructureservice-config"}}},{"name":"MONGO_URI","valueFrom":{"configMapKeyRef":{"key":"MONGO_URI","name":"powerinfrastructureservice-config"}}},{"name":"POD_SERVICE","value":"powerinfrastructureservice-service"}],"image":"soelmanm/smart-energy-system:powerinfrastructureservice","imagePullPolicy":"Always","name":"smart-energy-system","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: powerinfrastructureservice
  name: powerinfrastructureservice
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/powerinfrastructureservice
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: powerinfrastructureservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: powerinfrastructureservice
    spec:
      containers:
      - env:
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: powerinfrastructureservice-config
        - name: CASSANDRA_SEEDS
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_SEEDS
              name: powerinfrastructureservice-config
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              key: MONGO_URI
              name: powerinfrastructureservice-config
        - name: POD_SERVICE
          value: powerinfrastructureservice-service
        - name: RABBITMQ_SEED
          value: rabbitmq-rabbitmq-discovery
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: ZsGRLB5XpA9h
        image: soelmanm/smart-energy-system:powerinfrastructureservice
        imagePullPolicy: Always
        name: smart-energy-system
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
