apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":null,"generation":1,"labels":{"app.kubernetes.io/component":"mongo-server","app.kubernetes.io/name":"mongo"},"name":"mongo","namespace":"default","selfLink":"/apis/apps/v1/namespaces/default/statefulsets/mongo"},"spec":{"podManagementPolicy":"OrderedReady","replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"mongo-server","app.kubernetes.io/name":"mongo"}},"serviceName":"mongo-internal-service","template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"mongo-server","app.kubernetes.io/name":"mongo"}},"spec":{"containers":[{"command":["mongod","--replSet","rs0","--bind_ip","0.0.0.0","--smallfiles","--noprealloc"],"image":"mongo:3.4.10","imagePullPolicy":"IfNotPresent","name":"mongo","ports":[{"containerPort":27017,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/db","name":"mongo-persistent-storage"}]},{"env":[{"name":"MONGO_SIDECAR_POD_LABELS","value":"app.kubernetes.io/component=mongo-serverapp.kubernetes.io/name=mongo"},{"name":"KUBE_NAMESPACE","value":"default"},{"name":"KUBERNETES_MONGO_SERVICE_NAME","value":"mongo-internal-service"}],"image":"cvallance/mongo-k8s-sidecar","imagePullPolicy":"Always","name":"mongo-sidecar","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":10}},"updateStrategy":{"type":"OnDelete"},"volumeClaimTemplates":[{"metadata":{"creationTimestamp":null,"name":"mongo-persistent-storage"},"spec":{"accessModes":["ReadWriteOnce"],"dataSource":null,"resources":{"requests":{"storage":"1Gi"}},"volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]},"status":{"replicas":0}}
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/component: mongo-server
    app.kubernetes.io/name: mongo
  name: mongo
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/mongo
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongo-server
      app.kubernetes.io/name: mongo
  serviceName: mongo-internal-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mongo-server
        app.kubernetes.io/name: mongo
    spec:
      containers:
      - command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip
        - 0.0.0.0
        - --smallfiles
        - --noprealloc
        image: mongo:3.4.10
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
      - env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: app.kubernetes.io/component=mongo-server
        - name: KUBE_NAMESPACE
          value: default
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongo-internal-service
        image: cvallance/mongo-k8s-sidecar
        imagePullPolicy: Always
        name: mongo-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: mongo-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0
