apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":null,"generation":1,"labels":{"app.kubernetes.io/component":"servicediscovery-server","app.kubernetes.io/name":"servicediscovery"},"name":"servicediscovery","namespace":"default","selfLink":"/apis/apps/v1/namespaces/default/statefulsets/servicediscovery"},"spec":{"podManagementPolicy":"OrderedReady","replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"servicediscovery-server","app.kubernetes.io/name":"servicediscovery"}},"serviceName":"servicediscovery-internal-service","template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"servicediscovery-server","app.kubernetes.io/name":"servicediscovery"}},"spec":{"containers":[{"env":[{"name":"MULTIPLE_EUREKA_INSTANCES","valueFrom":{"configMapKeyRef":{"key":"MULTIPLE_EUREKA_INSTANCES","name":"servicediscovery-config"}}},{"name":"EUREKA_URI","valueFrom":{"configMapKeyRef":{"key":"EUREKA_URI","name":"servicediscovery-config"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_SERVICE","valueFrom":{"configMapKeyRef":{"key":"POD_SERVICE","name":"servicediscovery-config"}}}],"image":"soelmanm/smart-energy-system:servicediscovery","imagePullPolicy":"Always","name":"servicediscovery","ports":[{"containerPort":8761,"name":"registry","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"updateStrategy":{"type":"OnDelete"}},"status":{"replicas":0}}
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/component: servicediscovery-server
    app.kubernetes.io/name: servicediscovery
  name: servicediscovery
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/servicediscovery
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: servicediscovery-server
      app.kubernetes.io/name: servicediscovery
  serviceName: servicediscovery-internal-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: servicediscovery-server
        app.kubernetes.io/name: servicediscovery
    spec:
      containers:
      - env:
        - name: MULTIPLE_EUREKA_INSTANCES
          valueFrom:
            configMapKeyRef:
              key: MULTIPLE_EUREKA_INSTANCES
              name: servicediscovery-config
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: servicediscovery-config
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_SERVICE
          valueFrom:
            configMapKeyRef:
              key: POD_SERVICE
              name: servicediscovery-config
        image: soelmanm/smart-energy-system:servicediscovery
        imagePullPolicy: Always
        name: servicediscovery
        ports:
        - containerPort: 8761
          name: registry
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
status:
  replicas: 0
